---
  parser: babel-eslint
  parserOptions:
    ecmaVersion: 11
  plugins:
    - promise
  env:
    node: true
    es2020: true
  rules:
    camelcase:
      - error
      - properties: always
    no-console:
      - error
      - allow:
        - error
    strict:
      - error
      - global
    indent:
      - error
      - 2
      - SwitchCase: 1
    quotes:
      - error
      - single
    linebreak-style:
      - error
      - unix
    semi:
      - error
      - always
    no-trailing-spaces:
      - error
      - skipBlankLines: false
    vars-on-top: error
    max-len:
      - error
      - 100
      - ignoreStrings: true
    spaced-comment:
      - off
    comma-dangle:
      - error
      - always-multiline
    dot-notation:
      - error
      - allowKeywords: true
        allowPattern: ""
    dot-location:
      - error
      - property
    eqeqeq: error
    no-eq-null: error
    no-eval: error
    no-extend-native: error
    no-native-reassign: error
    no-extra-bind: error
    no-floating-decimal: error
    no-implied-eval: error
    no-loop-func: error
    no-multi-spaces:
      - error
      - ignoreEOLComments: true
    no-multi-str: error
    no-param-reassign: error
    no-return-assign: error
    no-self-compare: error
    no-sequences: error
    no-throw-literal: error
    no-unused-expressions: error
    no-void: error
    no-with: error
    radix: error
    wrap-iife:
      - error
      - outside
    no-implicit-coercion:
      - error
      - boolean: true
        number: true
        string: true
    one-var:
      - error
      - never
    no-constant-condition: 1
    no-warning-comments:
      - warn
      - terms:
          - todo
          - fixme
          - xxx
        location: anywhere
    array-bracket-spacing:
      - error
      - never
    no-return-await:
      - error
    brace-style:
      - error
      - 1tbs
      - allowSingleLine: true
    comma-spacing:
      - error
      - before: false
        after: true
    comma-style:
      - error
      - last
    computed-property-spacing:
      - error
      - never
    consistent-this:
      - error
      - self
    eol-last: error
    no-array-constructor: error
    no-nested-ternary: error
    no-new-object: error
    no-spaced-func: error
    space-before-function-paren:
      - error
      - anonymous: never
        named: never
    space-before-blocks:
      - error
      - always
    block-spacing:
      - error
    space-in-parens:
      - error
      - never
    space-infix-ops: error
    space-unary-ops:
      - error
      - words: true
        nonwords: false
    keyword-spacing:
      - error
      - before: true
        after: true
    semi-spacing:
      - error
      - before: false
        after: true
    padded-blocks:
      - error
      - never
    operator-linebreak:
      - error
      - after
      - overrides:
          "?": before
          ":": before
    operator-assignment:
      - error
      - always
    object-curly-spacing:
      - error
      - never
    curly:
      - error
    no-unneeded-ternary: error
    wrap-regex: error
    no-lone-blocks: error
    no-lonely-if: error
    no-continue: error
    no-inline-comments: off
    func-names: off
    func-style:
      - error
      - declaration
      - allowArrowFunctions: true
    id-length:
      - off
      - min: 3
        max: 10
        exceptions:
          - x
    key-spacing:
      - error
      - beforeColon: false
        afterColon: true
        #align: value
    max-nested-callbacks:
      - error
      - 3
    no-multiple-empty-lines:
      - error
      - max: 2
    arrow-body-style:
      - error
      - as-needed
    arrow-parens:
      - error
      - as-needed
    arrow-spacing:
      - error
      - before: true
        after: true
    constructor-super: error
    no-useless-constructor: error
    generator-star-spacing:
      - error
      - before: true
        after: false
    no-class-assign: error
    no-const-assign: error
    no-dupe-class-members: error
    no-duplicate-imports: error
    no-new-symbol: error
    no-this-before-super: error
    no-useless-computed-key: error
    prefer-const: error
    require-yield: error
    template-curly-spacing: error
    prefer-template: off
    prefer-rest-params: error
    global-require: error
    yield-star-spacing:
      - error
      - before
    prefer-arrow-callback: error
    no-var: error
    object-shorthand: error
    prefer-spread: error
    promise/param-names: error
    promise/always-return: 0
    promise/catch-or-return: 0
    promise/no-native: 0

  extends: eslint:recommended
